name: Lint SQL Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlfluff

    - name: Run SQLFluff on specific folder
      run: |
        echo "--- SQLFluff Output for SQL_Scripts ---" >> quality_check_output.txt
        sqlfluff lint $(git ls-files 'SQL_Scripts/*.sql') --dialect=bigquery >> quality_check_output.txt 2>&1
        if [ $? -ne 0 ]; then
          echo "SQLFluff linting failed for SQL_Scripts. Check quality_check_output.txt for details."
          exit 1
        fi

    - name: Run SQLFluff on all SQL files
      run: |
        echo "--- SQLFluff Output for All SQL Files ---" >> quality_check_output.txt
        sqlfluff lint $(git ls-files '*.sql') --dialect=bigquery >> quality_check_output.txt 2>&1
        if [ $? -ne 0 ]; then
          echo "SQLFluff linting failed for all SQL files. Check quality_check_output.txt for details."
          exit 1
        fi
      shell: bash

    - name: Display output
      run: cat quality_check_output.txt
