name: Code Quality Check

on:
  pull_request:
    branches:
      - main  # Or your desired branch

jobs:
  quality_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Or your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint # Example quality tools. Add your specific tools here.
          pip install mysql-connector-python
          pip install sqlfluff

      - name: Create Output File
        run: touch quality_check_output.txt  # Create an empty file to store output

      - name: Run quality checks (Flake8) and save output
        run: |
          echo "--- Flake8 Output ---" >> quality_check_output.txt
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics >> quality_check_output.txt 2>&1
          echo "--- End Flake8 Output ---" >> quality_check_output.txt


      - name: Run SQL quality checks (sqlfluff) and save output
        run: |
          echo "--- SQLFluff Output ---" >> quality_check_output.txt
          sqlfluff lint $(git ls-files 'SQL_Scripts\*.sql') --dialect=bigquery >> quality_check_output.txt 2>&1
          echo "--- End SQLFluff Output ---" >> quality_check_output.txt

      - name: Upload Output File as Artifact (Optional)
        uses: actions/upload-artifact@v4
        with:
          name: quality-check-report
          path: quality_check_output.txt