name: Lint Check Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlfluff
        pip install google.generativeai

    - name: Run Python script
      run: |
        echo "--- Running Python script for SQL checkks ---" >> quality_check_output.txt
        python py_Scripts/code_run_args.py >> quality_check_output.txt
      
      continue-on-error: true
      shell: bash
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.9.21/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.9.21/x64/lib
      

    - name: Display output
      run: cat quality_check_output.txt
